[tasks.build]
command = "cross"
args = ["build", "--target-dir=output", "--target=${@}"]

[tasks.release]
command = "cross"
args = ["build", "--frozen", "--target-dir=output", "--release", "--target=${@}"]