[tasks.createrelease]
condition = { env_set = ["TARGET", "OUTNAME"], fail_message = "TARGET/OUTNAME not specified" } 
command = "cross"
args = ["build", "--frozen", "--target-dir=output", "--release", "--target=${TARGET}"]

# We could potentially use @@ßplit here to run make on all targets, but the
# build will then sometimes fail and I'm not sure why. More reliable to always
# run them as separate commands.

#args = ["build", "--frozen", "--target-dir=output", "--release", "@@split(TARGET,|)"]


# Linux GNU targets
[tasks.release-x86_64-linux-gnu]
env = { TARGET = ["x86_64-unknown-linux-gnu"] }
run_task = "createrelease"

[tasks.release-aarch64-linux-gnu]
env = { TARGET = "aarch64-unknown-linux-gnu" }
run_task = "createrelease"

[tasks.release-x86-linux-gnu]
env = { TARGET = ["i686-unknown-linux-gnu"] }
run_task = "createrelease"

[tasks.release-armv7-linux-gnueabihf]
env = { TARGET = "armv7-unknown-linux-gnueabihf" }
run_task = "createrelease"


# Android targets
[tasks.release-x86_64-android]
env = { TARGET = "x86_64-linux-android" }
run_task = "createrelease"

[tasks.release-aarch64-android]
env = { TARGET = "aarch64-linux-android" }
run_task = "createrelease"


# musl targets
# These are statically built, so will work on more platforms
[tasks.release-arm-linux-musleabi]
env = { TARGET = "arm-unknown-linux-musleabi" }
run_task = "createrelease"

[tasks.release-aarch64-linux-musl]
env = { TARGET = "aarch64-unknown-linux-musl" }
run_task = "createrelease"


[tasks.post-releases]
script = """
OUT="release/${CARGO_MAKE_PROJECT_VERSION}"
mkdir -p ${OUT};
ls output/ | while read line; do
	if test -d output/$line && test -f "output/${line}/release/${OUTNAME}"; then
		echo $line;
		if test -f ${OUT}/${OUTNAME}-${line}-${CARGO_MAKE_PROJECT_VERSION}.zip; then
			rm -f  ${OUT}/${OUTNAME}-${line}-${CARGO_MAKE_PROJECT_VERSION}.zip;
		fi
		zip -j ${OUT}/${OUTNAME}-${line}-${CARGO_MAKE_PROJECT_VERSION}.zip output/${line}/release/${OUTNAME}
	fi;
done
"""

[tasks.releases]
run_task = [
    { name = [
		"release-x86_64-linux-gnu", "release-aarch64-linux-gnu",
		"release-x86-linux-gnu", "release-armv7-linux-gnueabihf",
		"release-x86_64-android", "release-aarch64-android",
		"release-arm-linux-musleabi", "release-aarch64-linux-musl",
		"post-releases"
	] },
]

[tasks.createzips]
run_task = "releases"
