[tasks.fixfmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fixclippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features", "--fix"]

[tasks.fix]
dependencies = ["fixfmt", "fixclippy"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.clippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features"]

